Repository wecode-bootcamp-korea/23-1st-RushOur-frontend, pull requests merged in 2021-08, with the labels that each got.

#8 [23기 황도윤]ADD: subcategory image 추가
  public/images/subcategory/body.jpg
  public/images/subcategory/cleanser.jpg
  public/images/subcategory/dustingPowder.jpg
  public/images/subcategory/handAndFoot.jpg
  public/images/subcategory/lotion.jpg
  public/images/subcategory/shavingCream.jpg
Labels: Status: 리뷰 요청

#4 [23기 이수정] ADD : 메인 Aside 배너 , 레이아웃 , 푸터 구현
  package-lock.json
  public/data/MainAsideData.json
  public/data/MainListData.json
  public/data/cartData.json
  public/data/visualData.json
  public/images/con2_1.png
  public/images/con2_2.png
  public/images/con2_3.png
  public/images/cream01.png
  public/images/sign1.png
  public/images/sign2.png
  public/images/sign3.png
  public/images/sign4.png
  public/images/sign5.png
  public/images/sign6.png
  public/images/vis01.png
  public/images/vis02.png
  public/images/vis03.png
  public/index.html
  src/Routes.js
  src/asset/image/con3_1.png
  src/asset/image/con3_2.png
  src/asset/image/con3_3.png
  src/asset/image/con3_4.png
  src/asset/image/soap.jpg
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Nav/Nav.js
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/CartButton.js
  src/pages/Cart/CartListSection.js
  src/pages/Cart/CartTotalSection.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/MainAside/MainAside.js
  src/pages/Main/MainAside/MainAside.scss
  src/pages/Main/MainCarousel/MainCarousel.js
  src/pages/Main/MainCarousel/MainCarousel.scss
  src/pages/Main/MainContent/MainContent.js
  src/pages/Main/MainContent/MainContent.scss
  src/pages/Main/MainContent2/MainContent2.js
  src/pages/Main/MainContent2/MainContent2.scss
  src/pages/Main/MainList/MainList.js
  src/pages/Main/MainList/MainList.scss
  src/pages/Main/MainList/MainListCom.js
  src/pages/Main/MainList/MainListCom.scss
  src/pages/ProductList/ProductList.js
  src/styles/common.scss
  src/styles/reset.scss
Labels: Status: Conflict 해결 요청

#6 [23기 이지선(0601)] ADD : LOGIN & SIGNUP 레이아웃 및 기본 기능 구현 완료
  package-lock.json
  package.json
  public/images/rushour_logo.png
  src/Routes.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Login/SignUp.js
  src/pages/Login/SignUp.scss
  src/pages/ProductList/images/fakeHeader.png
Labels: Status: Accepted

#10 [23기 이수정] modify : 리뷰 수정사항 반영
  public/data/cartData.json
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/CartButton.js
  src/pages/Cart/CartListSection.js
  src/pages/Cart/CartTotalSection.js
  src/pages/Main/MainAside/MainAside.js
  src/pages/Main/MainAside/MainAside.scss
  src/pages/Main/MainCarousel/MainCarousel.js
  src/pages/Main/MainCarousel/MainCarousel.scss
  src/pages/Main/MainContent/MainContent.js
  src/pages/Main/MainContent/MainContent.scss
  src/pages/Main/MainContent2/MainContent2.scss
  src/pages/Main/MainList/MainList.js
  src/pages/Main/MainList/MainListCom.scss
Labels: Status: 리뷰 요청

#11 [23기 박정우] ADD: 장바구니 버튼 클릭시 백엔드에 데이터 전송
  public/data/cartData.json
  public/data/category.json
  public/data/productDetail/navigator.json
  src/Routes.js
  src/components/Cart/Cart.js
  src/components/Cart/Cart.scss
  src/components/Cart/CartButton.js
  src/components/Cart/CartListSection.js
  src/components/Cart/CartListSection/CartList.js
  src/components/Cart/CartTotalSection.js
  src/components/ProductDetail/Goods.js
  src/components/ProductDetail/Goods/GoodsInfo.js
  src/components/ProductDetail/Goods/GoodsInfo/GoodsAmount.js
  src/components/ProductDetail/Goods/GoodsInfo/GoodsBtn.js
  src/components/ProductDetail/Goods/GoodsInfo/GoodsChoice.js
  src/components/ProductDetail/Goods/GoodsInfo/GoodsHeader.js
  src/components/ProductDetail/Goods/GoodsInfo/GoodsItem.js
  src/components/ProductDetail/Goods/GoodsInfo/GoodsPurchase.js
  src/components/ProductDetail/Goods/Location.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
Labels: Status: Accepted

#12 [23기 이지선(0601)]MODIFY: API수정, 회원가입TOKEN 수정
  src/pages/Login/Login.js
  src/pages/Login/SignUp.js
Labels: Status: 리뷰 요청

#14 [23기 이수정] modify : 장바구니 수정
  src/pages/Cart/Cart.js
  src/pages/Cart/CartListSection.js
  src/pages/Cart/CartTotalSection.js
Labels: Status: 리뷰 요청

#15 [23기 이지선(0601)] ADD:SIGNUP 우편번호찾기API구현
  src/pages/Login/Login.js
  src/pages/Login/SignUp.js
Labels: Status: 리뷰 요청
